# Generated by Django 5.0.7 on 2024-07-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_donor',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
