# Generated by Django 5.0.7 on 2024-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_remove_usermodel_is_donor_alter_usermodel_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_donater',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
