# Generated by Django 5.0.7 on 2024-07-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0004_remove_usermodel_profile_image_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_image',
            field=models.ImageField(null=True, upload_to='pet_images'),
        ),
        migrations.DeleteModel(
            name='PetImage',
        ),
    ]
