# Generated by Django 5.0.7 on 2024-08-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0006_alter_profileimage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
