# Generated by Django 5.0.7 on 2024-08-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0007_remove_pet_is_approved_alter_pet_pet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
